### ISSUE TITLE
Documentation in Test2::Require::Perl has bad synopsis

### ISSUE THREAD

**Issue by kentfredric** [Test-More/Test2-Suite#1]
https://metacpan.org/source/EXODIST/Test2-Suite-0.000016/lib/Test2/Require/Perl.pm#L43
```perl
=head1 SYNOPSIS
 
    # Skip the test unless perl 5.10 or greater is installed.
    use Test2 Perl 'v5.10';
 
    # Enable 5.10 features.
    use v5.10;
 ```

**Comment by exodist** [comment]
sometimes a test may depend on a perl version, but not need the featues in the test itself. for instance testing a package that uses the 5.10 features.

however I can document that it does not turn the features on for you.

**Comment by kentfredric** [comment]
I think I failed to communicate the error:

`use Test2 Perl 'v5.10';`

^ is clearly a syntax error, because there's no "::Require::" and so the word "Perl" here is a bareword without a comma on either side of it.

**Comment by kentfredric** [comment]
```bash
perl -MO=Deparse -e 'use Test2 Perl q[v5.10]'
# syntax error at -e line 1, near "Perl q[v5.10]"
# -e had compilation errors.
```

**Comment by exodist** [comment]
Ooops, sorry, I did misunderstand, will fix.
