### ISSUE TITLE
DNE() with in_set() fails

### ISSUE THREAD

**Issue by alfiedotwtf** [Test-More/Test2-Suite#10]
Maybe I'm doing something wrong, but I would have expected that all of these tests should pass:

    #!/usr/bin/perl

    use strict;
    use warnings;

    use Test2::Bundle::Extended;

    my $check = hash {
      field first   => 42;
      field second  => undef;
      field third   => DNE();
      field fourth  => in_set(42, undef);
      field fifth   => in_set(42, undef);
      field sixth   => in_set(42, DNE());
      field seventh => in_set(42, DNE());
    };

    is(
      {
        first   => 42,
        second  => undef,
        # third DNE
        fourth  => 42,
        fifth   => undef,
        sixth   => 42,
        # seventh DNE <- fails :(
      },
      $check
    );

**Comment by alfiedotwtf** [comment]
Also note that flipping the in_set() to a not_in_set() also doesn't work as I expected:

    field seventh => not_in_set(99, D());

**Comment by dmaestro** [comment]
I've also run into this since your **excellent** talk at TPC (aka YAPC) Monday, and I've been trying out Test2. Would be nice to have an `E()` quick operator that does what `not_in_set(DNE())` _should_ do.

**Comment by exodist** [comment]
will fix, and probably gonna add E() as well.

**Comment by exodist** [comment]
Did all this on my flight home. Will push to github when I can.

**Comment by exodist** [comment]
Fixed in latest TRIAL release

**Comment by alfiedotwtf** [comment]
Awesome! Thanks. Currently on leave for a week, so will check them out when I get back.

**Comment by alfiedotwtf** [comment]
Looks good. Thanks!
