### ISSUE TITLE
test 4, t/modules/Util/Table.t fails if terminal columns < 80

### ISSUE THREAD

**Issue by thirdm** [Test-More/Test2-Suite#106]
The 4th test of t/modules/Util/Table.t fails iff my terminal has less than 80 columns. I've attached the output from make test TEST_FILE='t/modules/Util/Table.t'.

Looking at the end of term_size() the behaviour looks intentional, but it was surprising to me:
```
...
    return 80 if !$total;
    return 80 if $total < 80;
    return $total;
}
```

[testoutput.txt](https://github.com/Test-More/Test2-Suite/files/626399/testoutput.txt)

**Comment by exodist** [comment]
Hmm, there should be an override in the test to make it work, I will check

**Comment by exodist** [comment]
Indeed, there is a bug, the test is wrong. Test2 tables do assume at least 80 characters because less than 80 makes for crazy table contortions.
