### ISSUE TITLE
Boolean context work breaks downstream

### ISSUE THREAD

**Issue by exodist** [Test-More/Test2-Suite#115]
PR #113 broke Test2::Tools::EventDumper. Specifically it makes compare objects all false in boolean context, which is not right. I have reverted the PR until it can be corrected.

Test2::Tools::EventDumper caught the problem because it has a test where it constructs a compare object by first dumping what the code should be, eval'ing that code, and running conditionals, it considers the eval returning false to be a failure, since the compare objects all have boolean-false overloading all tests failed.

**Comment by exodist** [comment]
@djerius Ball is in your court, once you fix the problem I would be happy to merge the work in again.

**Comment by exodist** [comment]
see https://github.com/Test-More/Test2-Tools-EventDumper/issues/2 for info of the discovery.

**Comment by djerius** [comment]
Test2::Compare::Base 's bool overload always returns zero to trigger failures in Test2::Suite's test suite if boolean context was used inappropriately.  I didn't appreciate how that changed the public interface.
My apologies.

I'm working on a fix.

**Comment by exodist** [comment]
Closing this ticket as a new PR was created, discussion to happen there.
