### ISSUE TITLE
Can't use meta checks on arrays

### ISSUE THREAD

**Issue by andfarm** [Test-More/Test2-Suite#131]
Attempting to make an assertion about the size of an array:

```
use Test2::V0;
use Test2::Tools::Compare;

is([0], array {
    prop size => 1;
});
```

doesn't work:

> 'Test2::Compare::Array=HASH(…)' does not support meta-checks

This seems like it should work -- it's certainly a lot clearer than asserting that item 0 exists.

**Comment by exodist** [comment]
The original idea was that if you just want meta checks use the meta builder:
is([1], meta { prop size => 1 });
If you want to check both meta and regular then you have 2 options

Option 1: do 2 checks:

is([1], meta { prop size => 1 });
is([1], array { item 1; });
Option 2, nest an array check under meta:
is([1], meta { prop size => 1; prop this => array { item 1 })

That is all of course assuming this is a trivial example of something more complex. If you simply want to assert the value of some elements and insure there are no extra elements beyond it you have 'end':
is([1], array { item 1; end }) which will check the first item to make sure it is '1', then make sure there are no additional items in the array. This also works for bag and hash.

Now, I am open to arguments in favor of this feature, but I would like a compelling case where the options above are a burden compared to inline meta checks.

**Comment by exodist** [comment]
#177 has been merged which fixes this.
