### ISSUE TITLE
V 2.9e-05 is fu**ing ridiculous unless users are warned against using the module

### ISSUE THREAD

**Issue by ronsavage** [Test-More/Test2-Suite#16]
Unparsable version '2.9e-05' for prerequisite Test2::Suite treated as 2.9 at /home/ron/perl5/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/CPAN/Meta/Requirements.pm line 136.
Warning: prerequisite Test2::Suite 2.9 not found. We have 0.000029.

**Comment by exodist** [comment]
It looks like that is reading the version number from Test2-Suite juat fine as 0.000029. The problem os that it is parsing the version wrong in whatever you have that is requiring Test2-Suite. Wherver that is, you proba ly need to quote the version number as a string, right now it is incorrectly treated as a float.

I don't think this is a problem with Test2, but a problem in your tooling. I am open to bwing wrong here, but I need more information, such as a minimal reproduction script.

**Comment by ronsavage** [comment]
Hi Chad

Fair enough. I apologize - I should have been a bit more temperate with 
my terminology.

Also, I did not check your source - I assumed you had chosen that 
representation of the version # deliberately as a euphemism of a 
dev-style #. Obviously I was wrong.

Since I've never seen this before it took me a while to even consider 
the possibility that something in my toolchain was a fault, but now I'll 
assume that is indeed the case, and investigate.

On 01/05/16 22:40, Chad Granum wrote:
> It looks like that is reading the version number from Test2-Suite juat
> fine as 0.000029. The problem os that it is parsing the version wrong in
> whatever you have that is requiring Test2-Suite. Wherver that is, you
> proba ly need to quote the version number as a string, right now it is
> incorrectly treated as a float.
>
> I don't think this is a problem with Test2, but a problem in your
> tooling. I am open to bwing wrong here, but I need more information,
> such as a minimal reproduction script.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Test-More/Test2-Suite/issues/16#issuecomment-216039322>
>

-- 
Ron Savage - savage.net.au

**Comment by ronsavage** [comment]
The problem seems to be in the way CPAN::Meta::Requirements uses version in 2 different ways depending on whether the small version # is in PREREQ_PM or TEST_REQUIRES.
I've added commentary to the former and await enlightenment.
https://github.com/Perl-Toolchain-Gang/CPAN-Meta-Requirements/issues/30

**Comment by dolmen** [comment]
@ronsavage To reduce the risk of this kind of issues, you should quote versions in Makefile.PL.
Mandatory reading: http://www.dagolden.com/index.php/369/version-numbers-should-be-boring/

**Comment by ronsavage** [comment]
Indeed, I should have supplied rather more details.
