### ISSUE TITLE
Skips shown as OK

### ISSUE THREAD

**Issue by ambs** [Test-More/Test2-Suite#179]
I have a test that

````
use Test2::V0;

SKIP: {
   skip if something();
   ok(1);
}
done_testing()
````

but test harness instead of saying 'skipped' for that specific file, says `ok`. Is this the desired behaviour?

**Comment by exodist** [comment]
I think you are mixing 2 concepts.

There is a skip-all plan to be used to skip a whole file:

```
skip_all "reason" if something()
```

And the skip for skipping a block of assertions:

```
SKIP: {
   skip if something();
   ok(1);
}
```

The first outputs a TAP plan for skipping all:
```
1..0 # SKIP reason
```

The second outputs 1 or more ok's with a reason for the skip:
```
ok 1 - skipped test # skip
```

I just ran some tests and both behaviors are working as expected.

**Comment by ambs** [comment]
Thank you, @exodist, as I mentioned in IRC, I might be doing things wrongly. And that was the case. Thank you for the clarification.
