### ISSUE TITLE
The Class tools do not allow test description

### ISSUE THREAD

**Issue by autarch** [Test-More/Test2-Suite#19]
None pof `isa_ok`, `can_ok`, or `DOES_ok` allow a test description. This makes for a weird and easily forgettable API, where they are the outliers among all the test functions.

This wasn't a good idea for `Test::More`, and I'd hate to see `Test2::Suite` repeat that mistake. I think it'd be preferable to accept a single class or arrayref of classes (or methods, etc) and allow the third argument to be the test description.

**Comment by bluefeet** [comment]
I second this.  I recently converted a portion of @work's test suite to Test2::Suite and it pained me when I had to remove the messages from my `isa_ok()` checks.  /sadface

**Comment by exodist** [comment]
I will look into changing it to have this convention:

``` isa_ok($thing, @list) ```

AND

``` isa_ok($thing, \@list, $name) ```

Basically if the second argument is an arrayref it will use it as a list, and the third item will be the name. I will do this for all 3 functions. This will not break anything, but will allow what you guys are asking.

Not sure when I will have a chance for this, so if one of you guys wants to do it and submit a PR I would be happy to merge it.
