### ISSUE TITLE
I have written some more comparisons

### ISSUE THREAD

**Issue by dakkar** [Test-More/Test2-Suite#21]
First of all, thank you for the herculean work you've done. `Test2` is much nicer to work with than `Test::Builder` could ever be.

Now, I found myself in need of the functionality of `Test::Deep::bag`, and I couldn't find something equivalent for `Test2`. So I wrote it: [`Test2::Compare::Bag`](https://www.thenautilus.net/cgit/Sietima/tree/t/lib/Test2/Compare/Bag.pm), [`Test2::Tools::MoreCompare`](https://www.thenautilus.net/cgit/Sietima/tree/t/lib/Test2/Tools/MoreCompare.pm).

The latter also provides a `call_list` which behaves like `call` but evaluates the method in list context. `list_call $method => $result` is a shortcut for `call(sub{[$_->$method]},$result,$method)`

Should I release those packages to CPAN, or should I provide them here as a pull request? If the former, does anyone have a better name than `Test2::Tools::MoreCompare`?

**Comment by exodist** [comment]
I would be happy with a pull request, once these are documented and tested.

It looks like you probably copied Compare::Array to make Compare::Bag. I would appreciate it if the PR had 2 commits, one simply copying Compare::Array to Compare::Bag, then a second that makes changes to the file, this way I can easily see the differences.

**Comment by dakkar** [comment]
pull request sent  #22
