### ISSUE TITLE
Tests are consistently failing on perl 5.8

### ISSUE THREAD

**Issue by DrHyde** [Test-More/Test2-Suite#236]
See CPAN-testers results here: http://matrix.cpantesters.org/?dist=Test2-Suite%200.000141;perl=5.8.9;reports=1

**Comment by exodist** [comment]
Looks like I used an //= by mistake. I will patch it as soon as I have a moment.

**Comment by DrHyde** [comment]
Oops! sorry about the noise!

**Comment by DrHyde** [comment]
any chance of getting that PR merged/released?

**Comment by exodist** [comment]
done

**Comment by DrHyde** [comment]
Thanks

<fx: fires up CPAN-testing machines>

**Comment by DrHyde** [comment]
test PASS Test2-Suite-0.000142 (perl-5.8.9) x86_64-linux-thread-multi 4.9.0-8-amd64

Hurrah!
