### ISSUE TITLE
Add 'stringify_got' attribute to Test2::Compare::Custom

### ISSUE THREAD

**Issue by dboehmer** [Test-More/Test2-Suite#239]
I found Test2::Compare::Custom to be very comfortable for quickly implementing a custom check.

In my case I get an object and need to apply a custom comparison method. I want left and right side objects to be stringified. With Test2::Compare::Custom I could successfully display a custom OP string as well as CHECK string.

```perl
$expected->{some_hashkey} = Test2::Compare::Custom->new(
    name          => "$my_foobar",    # stringifies to "foo42"
    operator      => 'MyOp',
    stringify_got => 1,    # proposal: has no effect yet
    code          => sub { MyApp::Foobar->compare($_, $my_foobar) },
);  
```

```
# +-----------------------+-----------------------+------+-----------+-----+
# | PATH                  | GOT                   | OP   | CHECK     | LNs |
# +-----------------------+-----------------------+------+-----------+-----+
# | {some_hashkey}        | MyApp::Foobar=ARRAY(0 | MyOp | foo42     |     |
# |                       | x556bb359cb88)        |      |           |     |
# |                       |                       |      |           |     |
# | ...                   | <DOES NOT EXIST>      |      | 1         |     |
# +-----------------------+-----------------------+------+-----------+-----+
```

Would you consider adding a `stringify_got` attribute? I found that classes like Test2::Compare::Regex have such a method to control whether the left side is stringified for output.

I volunteer to implement a PR but wait for your approval first. Any thoughts on this?

**Comment by exodist** [comment]
Yes, I would merge such a pull request, seems like a good feature to add.

**Comment by dboehmer** [comment]
This was implemented by PR https://github.com/Test-More/Test2-Suite/pull/241 but this issues wasn’t closed for some reason :man_shrugging:
