### ISSUE TITLE
string() confesses when not defined

### ISSUE THREAD

**Issue by alfiedotwtf** [Test-More/Test2-Suite#24]
The docs say:

  Note: This will fail if the recieved value is undefined, it must be defined.

So when using string() as a quick check, it confesses when not defined. Shouldn't it simply return false if it is not a string?

**Comment by exodist** [comment]
I am not sure I follow. It was intentional that string(undef) confess. Can you explain the use case where this is a problem?

**Comment by alfiedotwtf** [comment]
Gah. Sorry my mistake.

While copying my code to paste in here, I realised this was a bug in my code!

Nothing to see here :)
