### ISSUE TITLE
Should dies() warn when called in void context?

### ISSUE THREAD

**Issue by dboehmer** [Test-More/Test2-Suite#243]
(I’ve stumbled over this a while ago but want to pick it up as we’ve just discussed my other issue and you merged my PR so quickly. Thanks for that! :+1: )

I was used to the old Test::Exception’s way of:

```perl
throws_ok { ... } qr/some error/;
```

When adopting Test2 I discovered `dies()`  and with just a glimpse over the docs I tried:

```perl
dies { ... }, qr/some error/;
```

That is pretty much a no-op but completely silent. At first I didn’t understand that I need to pass its output to e.g. `like`.

This is how `dies()` behaves in void context with different variations:

```console
$ perl -MTest2::V0 -e 'dies { die() }, qr/xxx/'
$ perl -MTest2::V0 -e 'dies { die() } qr/xxx/'
Too many arguments for Test2::Tools::Exception::dies at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
$ perl -MTest2::V0 -e 'dies { die() } qr/xxx/, "test name"'
Too many arguments for Test2::Tools::Exception::dies at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
$ perl -MTest2::V0 -e 'dies { die() }, qr/xxx/, "test name"'
Useless use of a constant ("test name") in void context at -e line 1.
```

For whatever reason Perl seems not to warn about the regex in void context (`$ perl -we 'qr/xxx/'` is silent).

Is the any useful application of `dies()` in void context? What do you think about making it warn about that?

**Comment by exodist** [comment]
dies in void context would be like an eval, except $@ is not altered. It is possible, though unlikely, that it is has been used that way. I am fine with making it warn in void context.
