### ISSUE TITLE
Document how to use `in_set` builder

### ISSUE THREAD

**Issue by KES777** [Test-More/Test2-Suite#246]
I read documentation and do not understand, how to test that `$got` value match one of expected values.

Would be nice to see examples how to accomplish this:
```perl
 is( 404, [ 202, 404 ], ... )
```

**Comment by KES777** [comment]
Like here: https://metacpan.org/pod/Test::Deep#any

**Comment by dakkar** [comment]
The relevant documentation is in Test2::Tools::Compare

It says that it «provides tools for building a data structure specification against which you can verify your data»

The main comparison tools are `is` (strict) and `like` (not strict); for the purpose of your question, the difference doesn't much matter, so let's use `is`.

The documentation for `is` says that it requires `$got` and `$expect` to be identical, unless `$expect` was build from a specification.

Now, I realise that "specification" is not very well explained; the section "quick checks" and later ones should probably come under a single "How to build specifications" section… but yes, "checks" and "specifications" are the same thing.

Therefore, `in_set` builds a specification requiring that the value under test match one or more of the values passed to `in_set`

With this, we can write:

```perl
is($number,in_set(3,4,5,6));
```

and that test will succeed if the `$number` is 3, 4, 5, or 6.

More complicated combinations are, of course, possible.

Does that help?

**Comment by KES777** [comment]
@dakkar 
Yes, thank you, you simple example did that!

**Comment by KES777** [comment]
Did documentation updated?.. =(
