### ISSUE TITLE
Dumper-on-fail for `is`, `isnt`, etc

### ISSUE THREAD

**Issue by tobyink** [Test-More/Test2-Suite#253]
The output when `is( $got, $expected )` fails is already pretty useful, but at times it helps to just see a full dump of `$got`. I very often find myself using the pattern:

```perl
is( $got, $expected, 'test name' ) or diag Dumper( $got );
```

It would be nice to be able to just do:

```perl
is( $got, $expected, 'test name' );
```

Then if `is` fails, Test2::Tools::Compare could check `$ENV{T2_DUMP_REFS}`, and if that venv var is true, provide a dump of `$got`. As an added bonus, if `$ENV{T2_DUMP_REFS} eq "DEPARSE"` it could turn on Data::Dumper's deparsing of coderefs.

I'm happy to submit of pull request for this myself if you think it would be a useful feature that you'd consider accepting.

**Comment by rabbiveesh** [comment]
`is` takes extra arguments which it will print as part of the diagnostics on failure. In situations where I want a full dump, i'll manually do
`is $got, $expected, 'test name', np $got`.

I think that's more useful behavior than the ENV var, b/c in most cases where you wanted to see the data once, you'll probably wanna see it again

**Comment by tobyink** [comment]
Still not ideal, as it involves eagerly dumping `$got` even in cases where the test passes. Plus if you're doing something like:

```perl
is(
  some_function_call(),
  $expected,
  'some_function_call() result was as expected',
);
```

I now need to create a lexical variable to store `$got` in.

**Comment by exodist** [comment]
@tobyink I would accept a PR that adds this functionality on an env var. Just make sure it is implemented in Test2::Tools::Compare and not Test2::Compare, people use that for validating structures outside of tests.

It might be nice to expand the functionality in other ways, but I will not hold up the PR on any requirements beyond what you specified here.

**Comment by tobyink** [comment]
Pull request submitted. Changed the name of the environment variables to `T2_AUTO_DUMP` and `T2_AUTO_DEPARSE` which seem clearer and more accurate, as they don't just dump references, but also non-reference values of `$got`.
