### ISSUE TITLE
Add some number inequality check functions

### ISSUE THREAD

**Issue by leonerd** [Test-More/Test2-Suite#258]
You can easily use `is()` to check if a number is exactly a given value, or use the `Test2::Tools::Compare::float()` function to make it approximate. But sometimes you want to test a number using one of the inequality operators. It'd be great if we had something like

```perl
$check = number_gt $min; # uses >
$check = number_ge $min; # uses >=
$check = number_le $max; # uses <=
$check = number_lt $max; # uses <
```

This would be especially useful combined with supporting is()-like testing in is_refcount() (#259).

**Comment by exodist** [comment]
oops, that last comment was meant for another issue, I will move it
