### ISSUE TITLE
Issue with moving Module::Pluggable to optional

### ISSUE THREAD

**Issue by michal-josef-spacek** [Test-More/Test2-Suite#262]
There was a change with moving Module::Pluggable to optional.

There is a code:
```
...
__PACKAGE__->plugins) {
...
```
In [Test2::Tools::Tester](https://github.com/Test-More/Test2-Suite/blob/master/lib/Test2/Tools/Tester.pm#L25) which uses Module::Pluggable.
1) This is bad as I understand

2) This cause error in tests (t/modules/Tools/Tester.t) in case when Module::Pluggable isn't used.
3) There is Module::Pluggable as dependency in t/00-report.t.

**Comment by exodist** [comment]
Pushed a fix to the test failures to cpan. The 00-report.t is not an issue, it will show it as not optional, but it will not cause a failure. I may fix that later.

**Comment by michal-josef-spacek** [comment]
Thanks, it's working well.

**Comment by michal-josef-spacek** [comment]
BTW: https://github.com/Test-More/Test2-Suite/pull/264
