### ISSUE TITLE
Question: What's a root cause of bundling Importer, Scope::Guard, and Sub::Info?

### ISSUE THREAD

**Issue by michal-josef-spacek** [Test-More/Test2-Suite#266]
Hi,
What's a root cause of bundling Importer, Scope::Guard, and Sub::Info?

I am packaging perl-Test2-Suite in Fedora and Fedora has rules to unbundle things.
See https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling

I understand that could be a sense of this activity, but I am trying to understand what's root cause.

Some Fedora consequences:
Importer and Scope::Guard modules have packages that depends on them.
```
> dnf repoquery --whatrequires 'perl(Importer)'
perl-Long-Jump-0:0.000001-9.fc37.noarch
perl-Sub-Info-0:0.002-19.fc37.noarch
perl-Term-Table-0:0.016-4.fc37.noarch
perl-Test2-Harness-0:1.0.133-1.fc37.noarch
perl-Test2-Suite-0:0.000150-1.fc37.noarch
```
and
```
> dnf repoquery --whatrequires 'perl(Scope::Guard)'
perl-Code-TidyAll-0:0.82-3.fc37.noarch
perl-DBIx-Class-0:0.082843-3.fc37.noarch
perl-LWP-UserAgent-DNS-Hosts-0:0.14-7.fc37.noarch
perl-Parallel-Prefork-0:0.18-20.fc37.noarch
perl-Test-File-ShareDir-0:1.001002-18.fc37.noarch
perl-Test2-Harness-0:1.0.133-1.fc37.noarch
perl-Test2-Suite-0:0.000150-1.fc37.noarch
perl-autobox-0:3.0.1-17.fc37.x86_64
```
But Sub::Info not. (only Test2::Suite)

**Comment by michal-josef-spacek** [comment]
Fedora ticket: https://bugzilla.redhat.com/show_bug.cgi?id=2190167

**Comment by exodist** [comment]
These are not bundled, they are inlined. The difference is that bundling would mean my package provides them for everyone. Inlining means I am implementing internal variations nobody else should use.

The reason is because we are trying to get Test2::Suite into perl core. This means anything it depends on needs to go to perl core as well. Scope::Guard, Sub::Info, and Importer cannot go into core for complicated political reasons. Because of this we decided inlined copies that are not available for others to use is the correct way to get Test2::Suite into Core without saying Core supports Importer, Scope::Guard or Sub::Info.

This package should not longer depend on Scope::Guard, Importer, or Sub::Info. And those 3 should continue to be packages own their own for things that do require them.

**Comment by michal-josef-spacek** [comment]
Ok, the root cause is moving to Perl Core.

The difference between inline (internal Perl module namespace) and bundling (external Perl module namespace) I understand.
The idea behind my question was the copying of the same code. It's basic programming nonsense.

btw: We have many dual-life modules (are in Perl Core and separated in CPAN) e.g. Archive::Tar (2.40 in perl-5.36.1 and 3.02 in separate version) in Fedora. There is only conflict between them and must have the same API.

In the case of Scope::Guard and Importer:
* Scope::Guard has the requirement to Carp and Exporter which are in Core. Test::More in testing too.
* Importer is without dependencies.
So there is no practical issue with placing these modules inside Perl Core too.

The same code means that each bug should be fixed in both places. And different namespaces are confusing.

That's something to think about it. :-)

**Comment by exodist** [comment]
The problem with Scope::Guard is something I am not sure of, I was told by others it was not politically viable to get it into core, I simply believe them.

The problem with Importer is that the perl core group are looking to implement an import tool, it may even one day be Importer.pm, but they do not want to allow Importer in core yet as it would look like core is approving of its use and deciding that is the one Core recommends for everyone to adopt..... so yeah, politics. I have learned not to get involved in politics and just do the menial labor to avoid politics.

**Comment by michal-josef-spacek** [comment]
@exodist Thank you for your answers. 

Do you have some links to the context? 
Do you know which Perl release (Perl Core) is prepared for this join? :-)

**Comment by exodist** [comment]
No, this was largely discussed in person at the Perl Toolchain Summit which is ongoing.
If it joins core (discussion ongoing) it will do so in 5.39.1 (which will be stable as 5.40.0 as far as I know, so a year from now)

**Comment by michal-josef-spacek** [comment]
ok, thanks.
