### ISSUE TITLE
Test2::Tools::Compare::{D,DF,F,T etc.) exported by default (contrary to docs)

### ISSUE THREAD

**Issue by jimav** [Test-More/Test2-Suite#271]
The pod for Test2::Tools::Compare says the "QUICK CHECKS" functions are not supposed to be exported by default, but they are (indirectly, by the Test2::V0 wrapper).   Those 1- and 2-character names do tend to pollute unwary user namespaces, so I agree with the intention stated in the docs.  https://metacpan.org/pod/Test2::Tools::Compare#QUICK-CHECKS

It might be hard to fix this without breaking downstream too much.
```
#!/usr/bin/env perl
use strict; use warnings; use feature qw/state say/;
use Test2::V0;

for my $name (qw/D DF F T Bogusxx/) {
  no strict 'refs';
  if (defined &{$name}) {
    warn "${name}() was imported\n"
  } else {
    warn "${name}() is not defined\n"
  }
}
```
OUTPUT:
```
D() was imported
DF() was imported
F() was imported
T() was imported
Bogusxx() is not defined
```

**Comment by rabbiveesh** [comment]
I think you're confusing the exports from the individual tool and Test2::V0.
I also very much disagree; in an actual test, you don't care about
namespace pollution and would rather the convenience
