### ISSUE TITLE
Should blead 'de-CUSTOMIZE` 4 test files changed to accommodate VMS?

### ISSUE THREAD

**Issue by jkeenan** [Test-More/Test2-Suite#282]
@Exodist, I want to double-check with you about synching Test2-Suite into the Perl core distribution.

VERSION '0.000156' of this distribution was synched into core (introduced, actually) in this commit:
```
git log --format=fuller -- cpan/Test2-Suite/lib/Test2/Suite.pm
commit 6281b77d53e56b6bed1ec4da419af7390d7b6785
Author:     Paul Evans <leonerd@leonerd.org.uk>
AuthorDate: Wed Sep 13 18:43:44 2023 +0100
Commit:     Paul Evans <leonerd@leonerd.org.uk>
CommitDate: Wed Sep 20 23:07:19 2023 +0100
```
Subsequently there were 2 commits to blead pertaining to cpan/Test2-Suite:
```
commit 34ae5b5cb645ef3f877b2152414d3059b5a95075
Author:     Graham Knop <haarg@haarg.org>
AuthorDate: Thu Oct 5 18:31:01 2023 +0200
Commit:     Graham Knop <haarg@haarg.org>
CommitDate: Thu Oct 5 20:34:47 2023 +0200

    Test2-Suite: remove problematic test
    
    Test2-Suite's t/acceptance/Workflow-Acceptance.t test is causing
    intermittent failures. Exodist has said:
```
... which meant that `t/acceptance/Workflow-Acceptance.t` is now marked as `EXCLUDED` in the `Porting/Maintainers.pl` entry for Test2::Suite; and ...
```    
commit aec81059a137b7e08424dc5dbaa763429003c05c
Author:     Craig A. Berry <craigberry@mac.com>
AuthorDate: Fri Oct 6 08:28:18 2023 -0500
Commit:     Craig A. Berry <craigberry@mac.com>
CommitDate: Fri Oct 6 14:53:05 2023 -0500

    Get Test2 tests working on VMS
    
    List assignment to %ENV is not supported, and mongrel filenames
    produced by concatenating hard-coded slashes with the return
    values from File::Spec functions don't work.

```
... wherein @craigberry modified 4 test files to work properly on VMS.  His doing so in blead first meant that for the October release we had to designate these 4 files as
```
1136     'Test2::Suite' => {
1137         'DISTRIBUTION' => 'EXODIST/Test2-Suite-0.000156.tar.gz',
1138         'SYNCINFO'     => 'LeoNerd on Wed Sep 14 10:44:29 2023',
1139         'FILES'        => q[cpan/Test2-Suite],
...
1148         'CUSTOMIZED'   => [
1149             qw( t/modules/Plugin/SRand.t
1150                 t/modules/Require/AuthorTesting.t
1151                 t/modules/Require/EnvVar.t
1152                 t/modules/Tools/GenTemp.t
1153               )
1154         ],
...
```
Now, inspecting https://github.com/Test-More/Test2-Suite/pulls?q=is%3Apr+is%3Aclosed, I see that in the past month you closed 2 pull requests in Test2-Suite, one from Craig, one from @Leont, both of which had to do with testing on VMS.  My hunch is that the 4 files now in https://metacpan.org/dist/Test2-Suite version 0.000159 should supersede those currently in blead marked `CUSTOMIZED` above.  That would mean that, in blead, I would remove the `CUSTOMIZED` element in `Porting/Maintainers.pl` and do a straightforward synch of Test2-Suite into blead in preparation for our November 20 release.

Can you confirm that what you've got in 0.000159 on CPAN is what should get synched into blead?

Thank you very much.
Jim Keenan

**Comment by exodist** [comment]
What I have should be synced into blead. I am not certain if all the vms issues were solved, but the PR's I was sent for them were merged.

**Comment by jkeenan** [comment]
> What I have should be synced into blead. I am not certain if all the vms issues were solved, but the PR's I was sent for them were merged.

Will do.  Thanks.
