### ISSUE TITLE
`done_testing` inside `fork_subtest` confuses the harness

### ISSUE THREAD

**Issue by dakkar** [Test-More/Test2-Suite#291]
Given this program:
```perl
use Test2::IPC;
use Test2::V0;
use Test2::Tools::AsyncSubtest;

subtest 'in process' => sub {
    pass 'all good';
    done_testing;
};

my $ff = fork_subtest 'forked' => sub {
    pass 'in sub-process';
    done_testing;
};
$ff->finish;

done_testing;
```

I would expect everything to pass. Instead, the forked sub-test fails with "Expected assertions: 0". Removing the `done_testing` from the forked subtest makes the problem go away. 

attached, the log generated by `yath -vL`
[2024-04-22_10:29:40_D7FBB8AC-008A-11EF-A60B-419F742278EF.json](https://github.com/Test-More/Test2-Suite/files/15060668/2024-04-22_10.29.40_D7FBB8AC-008A-11EF-A60B-419F742278EF.json)

This is with `Test2::Suite` 0.000159 and `Test2::API` 1.302198

**Comment by exodist** [comment]
fork_subtest is intended to be controlled from the parent process. AsyncSubtest in general is intended to have events come from any number of child processes, it is not possible for any child to know if any other child is finished, so it is the parent processes's job to call finish, which handles the done testing.

I think the answer here is that calling done_testing() in a child of an asyc subtest should throw an exception saying "Do not do that, here is why ...".

**Comment by dakkar** [comment]
oooh, right, the `Test2::AsyncSubtest` POD section for `->finish` does say:
> Finish the subtest, wait on children, and send the final subtest event

but yes, a mention in `Test2::Tools::AsyncSubtest` would certainly help!
