### ISSUE TITLE
Tools::Compare

### ISSUE THREAD

**Issue by desertfox** [Test-More/Test2-Suite#31]
#30 https://github.com/Test-More/Test2-Suite/blob/master/t/modules/Tools/Compare.t#L412

Confused to what the behavior here should be, Operator is '' when checking comparison operator of a string. So no OP is returned in the message.

**Comment by exodist** [comment]
Not sure I understand your bug report (question?) the line in question appears to assert that on that numerical comparison the '==' operator is used. But your actual question says string comparison gets no operator?

**Comment by exodist** [comment]
https://travis-ci.org/Test-More/Test2-Suite/jobs/140396423   this test failure indicates that your PR changed the behavior so that the operator of numerical comparisons is sometimes ''.

**Comment by exodist** [comment]
I see the issue in your PR. I am closing this ticket and will address it there.
