### ISSUE TITLE
Explicitly specify the license, not "same terms as Perl itself"

### ISSUE THREAD

**Issue by petdance** [Test-More/Test2-Suite#32]
I don't think there's any benefit in the "same terms as Perl itself" wording, and can only cause confusion.  If it's being licensed as Artistic License 2.0, then I think it makes sense to go ahead and specify it.

http://use.perl.org/use.perl.org/_Shlomi%2BFish/journal/36050.html has some discussion of this.

**Comment by rjbs** [comment]
Note that perl v5 is licensed as Artistic 1 or GPL 1, meaning that if this is to be bundled with Perl core, that needs to be an available option.

**Comment by petdance** [comment]
All the more reason to be specific in what the license is.

**Comment by schwern** [comment]
@petdance There's a link to the license in the docs and a complete [LICENSE file](https://metacpan.org/source/EXODIST/Test2-Suite-0.000058/LICENSE) with the source distribution. That's usually sufficient for anyone wanting to redistribute a module.

What else do you think we need?  And who's the audience that needs it?

**Comment by exodist** [comment]
5f36765 adds the liscence to the repo.
