### ISSUE TITLE
Create a "how to work on Test2::Suite" document

### ISSUE THREAD

**Issue by petdance** [Test-More/Test2-Suite#33]
Start with explaining that you have to use Dist::Zilla, not EU::MM, and how to use Dist::Zilla to do common tasks.  Not everyone uses it, and without a Makefile.PL, someone unfamiliar with Dist::Zilla will not understand what to do.

**Comment by autarch** [comment]
Alternatively, configure dzil to check in the generated Makefile.PL and other generated files (which you should do for the LICENSE and README anyway).

(My dzil bundle)[https://metacpan.org/release/Dist-Zilla-PluginBundle-DROLSKY] may be a useful place to steal things from. If you're using dzil for more than a few distros, I strongly encourage you to create your own bundle. It makes your life much easier, and can make it easier for other people who release your software.

Round tuits and all that, of course.

**Comment by petdance** [comment]
>  I strongly encourage you to create your own bundle

I'm not saying "I don't know how to use dzil". I'm saying "Not every person wanting to work on Test2::Suite will know how to use dzil, or even recognize that dzil is involved."  Even if someone said "Hmm, what's this dist.ini?" there's nothing in it to say "You have to use Dist::Zilla to use this."

> configure dzil to check in the generated Makefile.PL

I think that would solve the problem nicely, so long as there was something in the Makefile.PL that says "I'm autogenerated, so don't modify me."

**Comment by petdance** [comment]
There is literally nothing in the entire repo that says "You need to use Dist::Zilla".

````
(SVN) alester:~ $ git clone git@github.com:Test-More/Test2-Suite.git
Cloning into 'Test2-Suite'...
remote: Counting objects: 4266, done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 4266 (delta 35), reused 0 (delta 0), pack-reused 4153
Receiving objects: 100% (4266/4266), 655.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (3219/3219), done.
Checking connectivity... done.
(SVN) alester:~ $ cd Test2-Suite/
(master) alester:~/Test2-Suite $ ack Dist::Zilla
(master) alester:~/Test2-Suite $ ack dzil
(master) alester:~/Test2-Suite $
````

**Comment by autarch** [comment]
> I think that would solve the problem nicely, so long as there was something in the Makefile.PL that says "I'm autogenerated by dzil, so don't modify me."

https://github.com/houseabsolute/DateTime.pm/blob/master/Makefile.PL shows an example of what this looks like. It has exactly such a comment.

**Comment by autarch** [comment]
I agree about this being confusing. I really think the best practice is to copy all the relevant files into the repo. My bundle copies the following generated files on every release:

```
            Build.PL
            CONTRIBUTING.md
            LICENSE
            Makefile.PL
            README.md
            cpanfile
            ppport.h
```

Note that not every distro I maintain has all the files, so that list covers several different cases.

**Comment by exodist** [comment]
5f36765 adds a bunch of this stuff.
