### ISSUE TITLE
Checking An Empty ArrayRef Against A bag Always Passes

### ISSUE THREAD

**Issue by elderling** [Test-More/Test2-Suite#43]
It appears to be a problem with `Test2::Compare::Bag::deltas` but I couldn't devote further time to fixing it.

```perl
use Test2::Bundle::Extended;
use Test2::Tools::Compare qw( is bag item );

my $check = bag {
    item 'a';
    item 'b';
    end(); # Ensure no other elements exist.
};

is( [ ], $check, 'All of the elements from bag found!'); # passes but shouldn't

done_testing;
```

**Comment by dakkar** [comment]
Thank you for the report! I'm currently on holidays with limited connectivity, but I'll take a look on Saturday at the latest.

**Comment by petdance** [comment]
Also fails:

````
my $check = bag {
    item 'a';
    end(); # Ensure no other elements exist.
};  
is( [ ], $check, 'All of the elements from bag found!'); # passes but shouldn't
````

**Comment by petdance** [comment]
Also fails

````
my $check = bag {
    item 'a';
};  
is( [ ], $check, 'All of the elements from bag found!'); # passes but shouldn't
````

**Comment by exodist** [comment]
Figured the problem out:

The code checks each item we want against each item we have. The comparisons return deltas. If there is a check that has no deltas it is considered a pass. The logic here assumes no deltas = pass. Since there are not items to look at we get no deltas.

**Comment by exodist** [comment]
Would appreciate review of my PR.

**Comment by exodist** [comment]
actually, spotted another related bug, adding test and fix

**Comment by exodist** [comment]
actually, the other problem is bigger, will open a separate ticket.

**Comment by exodist** [comment]
See #45 for the other issue
