### ISSUE TITLE
The Exception tools should provide something like lives_ok

### ISSUE THREAD

**Issue by autarch** [Test-More/Test2-Suite#49]
If I expect something to live, I really want to get diagnostic of the exception when it doesn't. The `lives or note` idiom is really suboptimal.

Even if you don't want to add this, I'd at least update the docs to suggest something like `is( exception { ... }, undef, ... )`

**Comment by exodist** [comment]
https://metacpan.org/pod/Test2::Tools::Exception#bool-lives

The documentation makes note that it preserves $@ for you to look at. The documented recommendation is:

```ok(lives { ... }, "did not die") or note($@);```

Could also recommend ok($lives { ... }, $name, $@); which would accomplish the same result.

**Comment by autarch** [comment]
Yes, my point was that the recommended idiom is kind of tedious to write, and it's exactly the kind of thing that could be wrapped up in a convenience function.

**Comment by exodist** [comment]
Hmm, I was reluctant because of the regex matching itself in the exception bug... but I just realized that the correct case for lives_ok { ... } is that there be no exception, so it doesn't suffer from that problem...

I am +1 for adding ```lives_ok { ... }```
