### ISSUE TITLE
Add a comparison function to Test2::Tools::Compare for two boolean values

### ISSUE THREAD

**Issue by petdance** [Test-More/Test2-Suite#50]
I've got a function that I've been calling `bool_eq` that compares truthiness.  Consider this example, probably in the middle of a big loop that goes over a bunch of different test cases.

````
my $thingy = find_a_thingy();  # Either returns a Thingy object or undef.
if ( $expect_to_find_a_thingy ) {  # Are we expecting to find one?
    ok( $thingy, 'Found a thingy' );
}
else {
    ok( !$thingy, 'Should not find a thingy' );
}
````

`bool_eq` lets that be rewritten as:

````
bool_eq( find_a_thingy(), $expect_to_find_a_thingy );
````

Or something like:

````
bool_eq( scalar @errors, $should_have_errors );
````

The diagnostics on failure would tell what values came in and how they evaluated:

````
#   Failed test 'Should have no errors'
#   at foo.t line 8.
#          got: true (5)
#     expected: false (0)
````
````
#   Failed test 'Should have found at least one user'
#   at foo.t line 10.
#          got: false (0)
#     expected: true (1)
````

````
#   Failed test 'Should not find a Mech object'
#   at foo.t line 9.
#          got: true (WWW::Mechanize=HASH(0x3cca328))
#     expected: false (0)
````

**Comment by petdance** [comment]
Here's what I've been using, using old Test::Builder style.  I am not in love with the name `bool_eq` but I could never think of anything better.

````
=head2 bool_eq( $got, $expect [, $msg ] )

Checks that $got and $expect have the same truth values: Either both true or
both false.

=cut

sub bool_eq($$;$) { ## no critic ( Freenode::Prototypes )
    local $Test::Builder::Level = $Test::Builder::Level + 1; 

    my $got   = shift;
    my $expect   = shift;
    my $msg = shift;

    my $ok = ok( ($got && $expect) || (!$got && !$expect), $msg );

    if ( !$ok ) {
        for ( $got, $expect ) {
            my $tf  = $_ ? 'true' : 'false';
            my $val = $_ // 'undef';
            $_ = "$tf ($val)";
        }    
        return diag(<<"DIAGNOSTIC");
         got: $got
    expected: $expect
DIAGNOSTIC
    }    

    return $ok; 
}
````

**Comment by petdance** [comment]
<@rjbs>	ha, I said bool_eq before looking at the page
<@rjbs>	yeah, I still like bool_eq

**Comment by exodist** [comment]
Please see the above PR.

**Comment by petdance** [comment]
Being able to say `is( bool($this), bool($that) )` is a step in the right direction, but I'd still like a `bool_eq( $this, $that )` to reduce the redundant function calls.

**Comment by petdance** [comment]
Being able to say `is( bool($this), bool($that) )` is a step in the right direction, but I'd still like a `bool_eq( $this, $that )`  to reduce the redundant function calls.  OTOH, I can also see keeping ::Compare being as atomic is possible, and leave the `bool_eq()`s to wrapper functions.

**Comment by schwern** [comment]
As per discussions in Slack, I think Test2 should avoid a proliferation of `thing_eq` functions and instead focus on providing `thing` comparison tools for the `is`/`like` DSL.

A third party module like Test::Expressive can provide a "reads like English" interface wrapper.

**Comment by exodist** [comment]
Test2::Tools::Expressive would be more correct.
