### ISSUE TITLE
array, bag, and hash should add an implicit `end` when used with `is`.

### ISSUE THREAD

**Issue by schwern** [Test-More/Test2-Suite#56]
Test2::Tools::Compare says right in the SYNOPSIS that `is` is "strict checking, everything must match".

        # Strict checking, everything must match
        is(
            $some_hash,
            {a => 1, b => 2, c => 3},
            "The hash we got matches our expectations"
        );

But with `array`, `bag`, `hash` that expectation doesn't hold true.

```
use Test2::Bundle::Extended;

my $array = [1,2,3,4];

is $array, array { item 1; item 2; item 3; end; }, "array w/end";          # fail
is $array, [1,2,3],                                "array ref";            # fail
is $array, array { item 1; item 2; item 3; },      "array wo/end";         # pass

is $array, bag { item 2; item 3; item 1; end; },   "bag w/end";            # fail
is $array, bag { item 2; item 3; item 1; },        "bag wo/end";           # pass


my $hash = { foo => 23, bar => 42, baz => 99 };

is $hash, { foo => 23, bar => 42 },                "hash ref";             # fail
is $hash, hash { field foo => 23; field bar => 42; end; }, "hash w/end";   # fail
is $hash, hash { field foo => 23; field bar => 42 },       "hash wo/end";  # pass

done_testing;
```

* This is a trap for the user. It's unexpected for the writer and the reader. `is` is for equality. `like` is for matches. Having an `is` that does a match breaks that expectation.
* The mistake is invisible. When the user inevitably forgets `end` the test will silently pass. They won't be aware of your mistake.
* It breaks the expectation that `[1,2,3]` and `array { item 1; item 2; item 3; }` are equivalent.

It's caught me plenty of times, probably all my code that uses `hash` or `array` forgot to use `end`.

To avoid this, I would suggest that `is` add an implicit `end` to any comparison which can take it. This avoids a very common mistake, and it removes a very common exception to the behavior of `is` vs `like`.

As for backwards compatibility, I think we'll find that most folks are screwing this up too. It's early enough in Test2's lifespan that we can fix this before it spreads.

**Comment by schwern** [comment]
As for `object`... the behavior of `end` in `object` is undesirable. It's glassbox testing to say that an object must contain specific hash fields and should not be encouraged. I'd be happy to just eliminate it, or require the user to do `object { hash { ... }; ... }`.

**Comment by schwern** [comment]
It would also fix this problem.

```
use Test2::Bundle::Extended;

is [1,2,3], array { 1,2,3 };  # passes?!

done_testing;
```

**Comment by exodist** [comment]
This will only fix #59 for is(), like() will still be vulnerable.

**Comment by exodist** [comment]
My plan for this:

- Change the underlying attribute used to store 'end' to a 3-state: 0 (off) 1 (on) and undef (not specified). When 0 or 1 are specified it is absolute, regardless of which function is being used. If it is undef then it should do whatever the function specifies.
- Default is 'undef', 1 happens when someone uses end(), 0 happens when someone uses etc() which we will add.
- This will start off as a warning to anyone who's tests would break from this, to give people a chance to fix things
- The warning will be an exception if $ENV{AUTHOR_TESTING} is true, that way authors know about it when release-testing
- Eventually we change the behavior to be a failure, with a warning of the recent change
- Eventually remove the warning, just a failure.

**Comment by exodist** [comment]
Also of note: Compare objects can be re-used, so is() and like() MUST NOT modify them in any way, including changing the value from undef to 1 or 0.

**Comment by schwern** [comment]
#62 and #63 bring up the interesting question of whether this should pass:

    like [1,2,3,4,5], array { item 2; item 3; item 4; };

That is if we interpret `like` to mean "the LHS contains the RHS".

**Comment by exodist** [comment]
that should not pass, to make it pass:

    like [1,2,3,4,5], array { item 1 => 2; item 3; item 4; };

notice the difference, item can take an index, and the indexes between the previous and the specified are skipped.

**Comment by exodist** [comment]
(indexes must also be specified in order when specified, you cannot go back (too hard to implement)).

**Comment by schwern** [comment]
Yes, it doesn't currently pass. The question is whether it should.

**Comment by exodist** [comment]
#66 fixes the issue on the description of the ticket. As for the question on if your sample should pass, I do not believe it should, but I am not opposed to making ti pass if you want to make that effort, but please open a new ticket so we don't have too many issues in any single ticket.
