### ISSUE TITLE
Add `etc`

### ISSUE THREAD

**Issue by schwern** [Test-More/Test2-Suite#62]
As discussed in Slack and on #56, add `etc`. This explicitly states that an `array` or `hash` is not the complete specification regardless of being used by `is` or `like`.

Examples...

    # After #56, both of these will be better written as `like`.
    is [1,2,3], array { item 1; item 2; etc };
    is { foo => 23, bar => 42 }, hash { field foo => 23; etc };

This opens the opportunity for `etc` to appear in other parts of an `array`.

    # It contains 2 and 3 in that order
    is [1,2,3,4,5], array { etc; item 2; item 3; etc; };

    # It starts with 1 and ends with 5
    is [1,2,3,4,5], array { item 1; etc; item 5; };

**Comment by exodist** [comment]
interesting, the 'etc' between items kind of acts like the array filtering capability already present. I think there is also already a behavior to skip until match... but I might have dropped that at some point.

**Comment by schwern** [comment]
What array filtering capability?

**Comment by exodist** [comment]
https://github.com/Test-More/Test2-Suite/pull/66 fixes this ticket.

**Comment by exodist** [comment]
@schwern https://metacpan.org/pod/Test2::Tools::Compare#filter_items-my-remaining-_-...-return-filtered is the array filtering stuff.

**Comment by exodist** [comment]
#66 was merged.
