### ISSUE TITLE
st() DSL sub

### ISSUE THREAD

**Issue by exodist** [Test-More/Test2-Suite#85]
```st Type => ...```

the Type must be in 'Test2::Compare::Check::Type' unless a '+' prefix is given to mean absolute path

The arguments after the first must either be a value (so if type is 'Array' it should be an arrayref) or a builder subref.

The first argument passed into the builder must be the check being constructed so that you can directly manipulate it if desired.

**Comment by schwern** [comment]
You said a lot about the arguments. What does it do? Why is it called `st`?
