### ISSUE TITLE
Add an all_items(CHECK) for arrays

### ISSUE THREAD

**Issue by alfiedotwtf** [Test-More/Test2-Suite#9]
Most of my code lives in checks. This works nicely, especially when validating deep hashes.

However, I've found that it's a bit awkward when it comes to arrays - currently, array checks can only be called manually. This doesn't work when you don't know how many items in an array before executing.

What I'd like, is something along the lines of:

    my $is_below_ten = validator(sub {
      my (%params) = @_;

      return undef if $params{got} < 10;
    });

    is(
      [3, 4, 5],
      array {
        all_items $is_below_ten;
      }
    );

**Comment by alfiedotwtf** [comment]
Not sure if this should be in this ticket or a new one - all_items() needs the equivalent for hash{}:

    all_keys()
    all_values()

Although I can emulate all_items() with filter_items(), there's no equivalent for hash{} so you end up iterating manually within a validator().

**Comment by dmaestro** [comment]
Yes, please!

**Comment by exodist** [comment]
I will look into doing this.

**Comment by exodist** [comment]
I wrote some patches that do all of this on my flight home. Still need to write tests.

**Comment by exodist** [comment]
Fixed in latest TRIAL release

**Comment by alfiedotwtf** [comment]
Thanks again :)

**Comment by alfiedotwtf** [comment]
Again, looks good :)
