### ISSUE TITLE
Test2::Plugin::UTF8 globally setting a utf8 layer on STDOUT/STDERR is questionable

### ISSUE THREAD

**Issue by Grinnz** [Test-More/Test2-Suite#92]
Test2::Plugin::UTF8, among other things, sets a :utf8 layer on the global STDOUT and STDERR handles. While it will usually be used at a top level in a test file via Test2::Bundle::Extended or similar, it still doesn't seem like the most compatible idea. For example, if a test file uses Test2::Bundle::Extended as well as a library which is using Test::More (or another Test::Builder based tool), that library will assume that its test output needs to be encoded to UTF-8, resulting in double-encoded output. There may also be other failure cases I'm not thinking of, due to the global nature of the handles.

I don't know enough about the architecture to know the feasibility, but would it be possible to instead have Test2::Plugin::UTF8 set something internally in Test2 which then causes any output to be encoded before being passed to STDOUT/STDERR? Or is there another solution that would work without affecting the global handles?

**Comment by exodist** [comment]
The idea behind this plugin is to turn UTF8 on everywhere, both for tests and for regular handles. It is documented as such. If you are trying to use it in a scenario where that is not what you actually want then this is simply the wrong tool for the job.

**Comment by exodist** [comment]
I would not however be opposed to a flag you can pass in at import that tells it to leave STDERR and STDOUT alone.

**Comment by schwern** [comment]
I'm with Grinnz, tests should not modify the global environment in ways that will change the behavior of the code being tested.

Test2 doesn't need to alter STDOUT and STDERR to enable UTF8, it can use copies as Test::Builder did before.

**Comment by exodist** [comment]
Test2 already does use copies of STDERR and STDOUT.

This plugin does what it is documented to do, it updates all the Test2 internal handles to use utf8, and also modified STDOUT and STDERR.

If we want a UTF8 plugin that only changes the Test2 internals then we should write that plugin. We should not be modifying a plugin that does exactly what it is supposed to to be the different plugin you want.

As for Test2::Bundle::Extended, I don't want to change it after the fact, but when we move to the Test2::Bundle::V system we can discuss using the different utf8 plugin suggested.

**Comment by schwern** [comment]
@exodist The trouble is this behavior, documented or not, will paper over production Unicode bugs. Code that runs fine in tests may have encoding problems in production. This is bad.

I'll make an educated guess that the number of people who realize this is about 3: us. I'll also say that the number of people _knowingly_ relying on this feature is about 0 because if they are then their code doesn't actually work.

Rather than having to put a big "DO NOT ACTUALLY USE THIS" warning on Test2::Plugin::UTF8, a brand new module, we should fix it to remove the caveat. Or we can spend the next five years telling people "don't use the obviously named module Test2::Plugin::UTF8 to turn on UTF8".

**Comment by exodist** [comment]
I understand the problem, but I also question it. Anyone who is testing output will need to capture or mask the output, which means bypassing STDERR and STDOUT anyway. I think the more common thing will be people trying to print diagnostics inline in their code while debugging why a test is failing, and this prevents them from needing to jump through extra hoops to add that debugging. (diag and note are not applicable here because I expect the debugging to be in non-test code that is being tested)

**Comment by exodist** [comment]
Give me a concrete example of this interfering with a test where you verify something outputs utf8 and I will relent, but I suspect anything you can do to intercept that output will make this a non-issue.

One possible exception I can see is this preventing warnings from happening when something actually outputs to STDERR/STDOUT, but that is far from ideal anyway, nobody should be doing that in a test, it interfers with TAP output and is unnecessarily noisy.

**Comment by schwern** [comment]
> Give me a concrete example of this interfering with a test where you verify something outputs utf8 and I will relent.

This should be the other way around. The assumption should be that modifying the global environment will have consequences and the burden is on it to provide a very good justification. But you already gave a solid example. ;)

> (diag and note are not applicable here because I expect the debugging to be in non-test code that is being tested)

Bingo. If they're trying, in a test, to run Unicode through production code that is not prepared to handle it that should not be papered over by the test.

Let's say they're testing a function that's going to be used to display a web page.

```
$ cat ~/tmp/html.pl 
sub make_html {
    my $text = shift;
    my $html = "<tag>$text</tag>";
    return $html;
}

sub print_html {
    print make_html(@_);
}

1;
```

They write a test for it.

```
$ cat ~/tmp/test.t
require "html.pl";

use Test2::Bundle::Extended;

my $thing = "Métal";
is make_html($thing), "<tag>$thing</tag>";

done_testing;
```

Coverage says they didn't test `print_html`. They could capture it and test it, but maybe that's really complicated, or like a lot of people don't know about the capture libraries. Maybe the printing function outputs an entire web page, not just a fragment, so it's hard to write an automated test. Maybe there's a lot of overhead to running the code that the test does for them. Maybe they just get lazy. For whatever reason they call `print_html($thing)` in the test and just eyeball it. It looks great! Manual verification, you know all about that. ;)

They push it to production and users complain about garbled characters. That's potentially hours of head scratching and debugging.

Another is people who write Perl like glorified shell and do a lot of piping of STDOUT. I don't code that way so I can't really give specifics, but I'm sure you could find some amazing stuff in the code at your $job.

For many, testing is the primary way developers will interact with their code and learn about it before release. Devs *still* don't think about encoding. If a developer adds debugging print statements and gets garbage that forces them to think about encoding.

The hard part of Unicode + Test::More was getting the formatters setup. It required a bunch of special code. Test2::Plugin::UTF8 covers that, that's good. In contrast setting up STDOUT/ERR is trivial and known, `use utf8:all` or `use open ":std", ":utf8"`. This minor benefit is outweighed by modifying the global environment and papering over encoding bugs.

**Comment by exodist** [comment]
I feel like this needs to be re-opened and discussed further.

When the global STDERR and STDOUT are not set we end up in a mixed-encoding output. People put unicode in their Test2 stuff, but then also use a print to display some diagnostics (yes they should use diag, but we are not talking theory, we are talking practice, and in practice people often just throw in a print.)

This mixed encoding output is a real problem, specially if things are redirected to files and opened later.

When you run a test you expect STDERR and STDOUT to containthe output of your test script. The STDERR and STDOUT do not belong to the libraries you load, they belong to the test. If the test is configured to produce UTF8, that should also effect FILENOs 0, 1, and 2, not just our copies of them.

If the code you are testing needs to use STDERR and STDOUT then it is the test writers responsibility to set them up separate and correct during the test, but before that happens the handles should get the same encoding as the internal copies.
