### ISSUE TITLE
Spurious test failure on Windows due to hard coded path separator in test file

### ISSUE THREAD

**Issue by nanis** [Test-More/Test2-Suite#97]
[This test][1] fails when using `perl` compiled on Windows using Visual Studio tools because paths are separated using **`\`** instead of **`/`**. Using Perl's builtin **`$0`** instead of the hard coded file name avoids the spurious failure.

[1]: https://github.com/Test-More/Test2-Suite/blob/969c6bd1245e51cc39b53ec70752ff08e41cc0fd/t/modules/Tools/Defer.t#L121

**Comment by exodist** [comment]
ah, I fixed this test in a branch that got abandoned, I will fix it again, thanks!
